# -*- coding: utf-8 -*-
"""sensor_id_updated-09-FEB-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EdZBNsk1229r3tLo11w5VLmAPfwRz-0Z
"""

!pip install torch
!pip install torch-geometric

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch_geometric.nn as pyg_nn

class AdvancedTemporalGraphNetwork(nn.Module):
    def __init__(self, num_features, hidden_channels, num_nodes, dropout=0):
        super(AdvancedTemporalGraphNetwork, self).__init__()
        self.init_params = {
            'num_features': num_features,
            'hidden_channels': hidden_channels,
            'num_nodes': num_nodes,
            'dropout': dropout
        }
        self.feature_reducer = nn.Linear(num_features, hidden_channels)
        self.graph_conv1 = pyg_nn.SAGEConv(hidden_channels, hidden_channels)
        self.graph_conv2 = pyg_nn.SAGEConv(hidden_channels, hidden_channels)
        self.dropout = nn.Dropout(p=dropout)
        self.temporal_lstm = nn.LSTM(
            input_size=hidden_channels,
            hidden_size=hidden_channels,
            num_layers=2,
            batch_first=True,
            dropout=dropout
        )
        self.temporal_attention = nn.MultiheadAttention(
            embed_dim=hidden_channels,
            num_heads=2,
            batch_first=True,
            dropout=dropout
        )

        # Prediction head now outputs only 1 value for pm2p5
        self.prediction_head = nn.Sequential(
            nn.Linear(hidden_channels, hidden_channels // 2),
            nn.ReLU(),
            nn.Dropout(p=dropout),
            nn.Linear(hidden_channels // 2, 1)  # Output size set to 1
        )

    # Update your model's forward method to handle the sequence properly:
    def forward(self, x, edge_index, time_sequence):
        """
        Forward pass through the network
        Args:
          x: Input features tensor [batch_size, num_nodes, num_features]
          edge_index: Graph connectivity [2, num_edges]
          time_sequence: Temporal sequence data [batch_size, sequence_length, num_features]
        Returns:
          predictions: PM2.5 predictions [batch_size, 1]
        """
        num_features = self.init_params['num_features']
        num_nodes = self.init_params['num_nodes']
        batch_size = x.shape[0]
        if x is None:
          x = torch.randn(batch_size, num_nodes, num_features, device=edge_index.device)
        x = x.float()

        time_sequence = time_sequence.float()

        # Reshape the input tensor to match the expected shape
        x_flat = x.view(-1, num_features)  # Flatten the batch and nodes dimensions

        # Apply feature reduction and graph convolutions
        spatial_features = self.feature_reducer(x_flat)
        spatial_features = self.dropout(F.relu(self.graph_conv1(spatial_features, edge_index)))
        spatial_features = self.dropout(F.relu(self.graph_conv2(spatial_features, edge_index)))

        # Reshape back to sequence format
        spatial_features = spatial_features.view(batch_size, num_nodes, -1)

        # Process temporal features
        # Reshape and reduce temporal features
        time_flat = time_sequence.view(-1, num_features)
        temporal_features = self.feature_reducer(time_flat)
        temporal_features = temporal_features.view(batch_size, -1, temporal_features.size(-1))

        # Apply LSTM and attention
        lstm_out, _ = self.temporal_lstm(temporal_features)
        attn_out, _ = self.temporal_attention(lstm_out, lstm_out, lstm_out)

        # Combine spatial and temporal features
        # Take the mean of spatial features across nodes and add to temporal features
        combined_features = attn_out[:, -1, :] + spatial_features.mean(dim=1)

        # Generate final predictions
        predictions = self.prediction_head(combined_features)

        return predictions

print(f'Model Compiled')

"""Process"""

import os
from google.colab import drive
drive.mount('/content/drive')
# Load and preprocess the data
root_path = '/content/drive/MyDrive/Intellipaat-sem2/AirPollutionAnalysis/RG'
future_predictions_15min = f'{root_path}/pm2p5_output/future_predictions_15min.csv'


input_path= f'{root_path}/input/120'
best_model_path=f'{root_path}/best_model/best_model.pth'

plot_path=f'{root_path}/plot'

combined_df =None

print(f'Drive Mounted - Input Path assigned {input_path}')
print(f'Drive Mounted - Best Model Path assigned {best_model_path}')
print(f'Drive Mounted - Plot Path assigned {plot_path}')



import pandas as pd
# Get the list of all files and directories
def list_files_of_a_dir(foldername):
    dir_path = f'{foldername}'
    dir_list = os.listdir(dir_path)
    return dir_list

dir_list = list_files_of_a_dir(input_path)
print(f"Files and directories in {input_path}")
for a in dir_list:
  print(a)

import os
import pandas as pd

def load_all_csv():
    input_dir = f'{input_path}'
    print(f'input_dir:{input_dir}')
    list_file = list_files_of_a_dir(input_dir)
    dataframes = []
    print("Step 02: Loading selected columns from all CSVs into DataFrames")
    selected_columns = ['sensor_id', 'timestamp', 'temperature', 'humidity', 'longitude', 'latitude', 'pm2p5']
    i = 0
    for f_name in list_file:
        if f_name.endswith(".csv") and "station" not in f_name.lower():
            # Build the full file path
            csv_path = os.path.join(input_dir, f_name)

            try:
                # Read the CSV file into a DataFrame with selected columns
                df = pd.read_csv(csv_path, usecols=selected_columns)
                dataframes.append(df)
                print(f"    {i}.    Loaded: {csv_path}")
                i += 1
            except Exception as e:
                print(f"Error reading {csv_path}: {e}")

    if dataframes:
        combined_df = pd.concat(dataframes, ignore_index=True)
        combined_df = combined_df[selected_columns]  # Ensure columns are in the specified order
        print(combined_df.columns.tolist())
        print(f"Step 03: Clubbed selected columns from all CSVs into a dataset. Dataset Shape: {combined_df.shape}")
    else:
        print("No valid CSV files found.")
        combined_df = None

    return combined_df

df = load_all_csv()

print(df)

import matplotlib.pyplot as plt

plt.hist(df['pm2p5'], bins=20, color='blue')
plt.xlabel('PM2.5')
plt.ylabel('Frequency')
plt.title('Histogram of PM2.5')

plt.savefig(f'{plot_path}/histogram_before_outliers_plot.png')
plt.show()
plt.close()

import pandas as pd

def find_outliers_iqr(data, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    print(f'IQR : {IQR}')
    lower_bound = Q1 - 1.5 * IQR
    print(f'lower_bound : {lower_bound}')
    upper_bound = Q3 + 1.5 * IQR
    print(f'upper_bound : {upper_bound}')
    outliers = data[(data[column] < lower_bound) | (data[column] > upper_bound)]
    return outliers

# Example usage:
outliers = find_outliers_iqr(df, 'pm2p5')
print(outliers)

import matplotlib.pyplot as plt
import seaborn as sns

# Assuming your DataFrame is named 'df':
sns.boxplot(x=df['pm2p5'])  # Use seaborn for a more visually appealing boxplot
plt.xlabel('PM2.5')
plt.title('Boxplot of PM2.5')
plt.savefig(f'{plot_path}/boxplot_before_outliers_plot.png')
plt.show()

plt.close()

top_50_pm2p5 = df.sort_values(by=['pm2p5'], ascending=True).head(50000)['pm2p5']
print(top_50_pm2p5)

top_50_pm2p5 = df.sort_values(by=['pm2p5'], ascending=False).head(15000)['pm2p5']
print(top_50_pm2p5)

# Importing
import sklearn
from sklearn.datasets import load_diabetes
import pandas as pd
import numpy as np

# Create the dataframe
df_pm2p5 =  df.copy()
df_pm2p5.head()
print("Old Shape: ", df_pm2p5.shape)

''' Detection '''
# IQR
# Calculate the upper and lower limits
Q1 = df_pm2p5['pm2p5'].quantile(0.25)
Q3 = df_pm2p5['pm2p5'].quantile(0.75)
IQR = Q3 - Q1
print(f'IQR:{IQR}')
lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

# Create arrays of Boolean values indicating the outlier rows
upper_array = np.where(df_pm2p5['pm2p5'] >= upper)[0]
lower_array = np.where(df_pm2p5['pm2p5'] <= lower)[0]

# Removing the outliers
df_pm2p5.drop(index=upper_array, inplace=True)
df_pm2p5.drop(index=lower_array, inplace=True)
df_pm2p5 = df_pm2p5[df_pm2p5['pm2p5'] > 0]

# Print the new shape of the DataFrame
print("New Shape: ", df_pm2p5.shape)

import matplotlib.pyplot as plt
import seaborn as sns

# Assuming your DataFrame is named 'df':
sns.boxplot(x=df_pm2p5['pm2p5'])  # Use seaborn for a more visually appealing boxplot
plt.xlabel('PM2.5')
plt.title('Boxplot of PM2.5')
plt.savefig(f'{plot_path}/boxplot_after_outliers_plot.png')
plt.show()

plt.close()

import matplotlib.pyplot as plt

plt.hist(df_pm2p5['pm2p5'], bins=20, color='blue')
plt.xlabel('PM2.5')
plt.ylabel('Frequency')
plt.title('Histogram of PM2.5')
plt.savefig(f'{plot_path}/histogram_after_outliers_plot.png')

plt.show()
plt.close()

top_50_pm2p5 = df_pm2p5.sort_values(by=['pm2p5'], ascending=True).head(50000)['pm2p5']
print(top_50_pm2p5)

top_50_pm2p5 = df_pm2p5.sort_values(by=['pm2p5'], ascending=False).head(15000)['pm2p5']
print(top_50_pm2p5)

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_percentage_error
import torch
from torch import nn, optim
import matplotlib.pyplot as plt

df = df_pm2p5.copy()
print(df.columns)
#pd.read_csv(data)
df['timestamp'] = pd.to_datetime(df['timestamp'])

df['year'] = df['timestamp'].dt.year
df['month'] = df['timestamp'].dt.month
df['day_of_month'] = df['timestamp'].dt.day
df['hour'] = df['timestamp'].dt.hour
df['minute'] = df['timestamp'].dt.minute
df['second'] = df['timestamp'].dt.second

df = df.drop(columns=['timestamp'])

columns = list(df.columns)
columns.remove('pm2p5')
#columns.remove('_id')
columns.append('pm2p5')
df = df[columns]

# Define constants
n_steps = 5
scalers_X, scalers_y = {}, {}
sensor_ids = df['sensor_id'].unique()
print(f'sensor_ids : {sensor_ids}')
# Create sequences and scale data by sensor_id
def scale_features(df, sensor_id):
    scaler_X = MinMaxScaler()
    scaler_y = MinMaxScaler()
    df_sensor = df[df['sensor_id'] == sensor_id]
    print(f'scale_features->df_sensor==>')
    print(f'{df_sensor}')
    print(f'<==')
    X = df_sensor.drop(columns=['sensor_id', 'pm2p5']).to_numpy()
    y = df_sensor['pm2p5'].to_numpy()

    X_scaled = scaler_X.fit_transform(X)
    y_scaled = scaler_y.fit_transform(y.reshape(-1, 1)).flatten()
    scalers_X[sensor_id] = scaler_X
    scalers_y[sensor_id] = scaler_y
  #  print(f'scalers_X==>{scalers_X}')
  #  print(f'scalers_y==>{scalers_y}')

  #  print(f'X_scaled[sensor_id={sensor_id}]:{X_scaled}')
  #  print(f'y_scaled[sensor_id={sensor_id}]:{y_scaled}')
    return X_scaled, y_scaled

def create_sequences(X, y, n_steps):
    Xs, ys = [], []
    for i in range(len(X) - n_steps + 1):
        Xs.append(X[i:i+n_steps])
        ys.append(y[i+n_steps-1])
    return np.array(Xs), np.array(ys)

# Scale and sequence the data
X_seq_combined, y_seq_combined = [], []
print(f'before for loop sensor_ids:{sensor_ids}')

for sensor_id in sensor_ids:
    print(f'in for loop sensor_id:{sensor_id}')
    X_scaled, y_scaled = scale_features(df, sensor_id)
    X_seq, y_seq = create_sequences(X_scaled, y_scaled, n_steps)
    X_seq_combined.append(X_seq)
    y_seq_combined.append(y_seq)

print(f'0. Length X_seq_combined:{len(X_seq_combined)}')
print(f'0. Length y_seq_combined:{len(y_seq_combined)}')

X_seq_combined = np.concatenate(X_seq_combined, axis=0)
y_seq_combined = np.concatenate(y_seq_combined, axis=0)

print('Flattening the 2 lists X_seq_combined, y_seq_combined')
print(f'1. Length X_seq_combined:{len(X_seq_combined)}')
print(f'1. Length y_seq_combined:{len(y_seq_combined)}')

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_seq_combined, y_seq_combined, test_size=0.2, random_state=42)

# Convert to tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

"""train"""

def create_distance_based_edge_index(df, threshold_km=5.0):
    """
    Create edge index based on geographical distance between sensors
    Args:
        df: DataFrame containing 'sensor_id', 'latitude', 'longitude'
        threshold_km: Maximum distance in kilometers for creating an edge
    Returns:
        edge_index: torch tensor of shape [2, num_edges]
    """
    def haversine_distance(lat1, lon1, lat2, lon2):
        """Calculate the great circle distance between two points on Earth"""
        R = 6371  # Earth's radius in kilometers

        # Convert decimal degrees to radians
        lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])

        # Haversine formula
        dlat = lat2 - lat1
        dlon = lon2 - lon1
        a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
        c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))
        distance = R * c

        return distance

    # Get unique sensor locations
    sensor_locations = df.groupby('sensor_id')[['latitude', 'longitude']].mean().reset_index()
    num_sensors = len(sensor_locations)

    # Initialize lists to store edges
    edges_source = []
    edges_target = []

    # Create edges based on distance threshold
    for i in range(num_sensors):
        for j in range(i + 1, num_sensors):  # Only compute upper triangle to avoid duplicates
            distance = haversine_distance(
                sensor_locations.iloc[i]['latitude'],
                sensor_locations.iloc[i]['longitude'],
                sensor_locations.iloc[j]['latitude'],
                sensor_locations.iloc[j]['longitude']
            )

            if distance <= threshold_km:
                # Add edges in both directions for undirected graph
                edges_source.extend([i, j])
                edges_target.extend([j, i])

    # If no edges were created based on distance, create a minimum spanning tree
    if not edges_source:
        print("Warning: No edges created based on distance threshold. Creating minimum connectivity...")
        for i in range(num_sensors - 1):
            edges_source.extend([i, i+1])
            edges_target.extend([i+1, i])

    # Create self-loops for each node
    for i in range(num_sensors):
        edges_source.append(i)
        edges_target.append(i)

    # Convert to tensor
    edge_index = torch.tensor([edges_source, edges_target], dtype=torch.long)

    # Ensure the edge_index is on the same device as the model
    if torch.cuda.is_available():
        edge_index = edge_index.cuda()

    print(f"Created edge_index with shape: {edge_index.shape}")
    print(f"Number of nodes: {num_sensors}")
    print(f"Number of edges: {edge_index.shape[1]}")

    return edge_index

# Usage in the training code:
edge_index = create_distance_based_edge_index(df)

import time
import torch

print(X_train_tensor.shape)
# Define and train the model
num_features = X_train_tensor.shape[2]
num_nodes = X_train_tensor.shape[1]
model = AdvancedTemporalGraphNetwork(num_features=num_features, hidden_channels=16, num_nodes=num_nodes, dropout=0.2)
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Example edge_index (replace with actual edge_index for your graph data)
# edge_index = torch.tensor([[0, 1, 2], [1, 2, 0]], dtype=torch.long)  # Dummy edge_index

num_epochs = 300
train_losses, train_rmse_values, train_r2_values, train_mape_values = [], [], [], []
test_losses, test_rmse_values, test_r2_values, test_mape_values = [], [], [], []

best_train_predictions, best_test_predictions = None, None
best_train_loss, best_test_loss = float('inf'), float('inf')

best_model_path = f'{best_model_path}/best_model.pth'
print(f'best_model_path {best_model_path}')

for epoch in range(num_epochs):
    start_time = time.time()  # Record start time

    model.train()
    optimizer.zero_grad()
    predictions_train = model(X_train_tensor, edge_index, X_train_tensor)
    train_loss = criterion(predictions_train.squeeze(), y_train_tensor)
    train_loss.backward()
    optimizer.step()
    train_losses.append(train_loss.item())

    model.eval()
    with torch.no_grad():
        predictions_test = model(X_test_tensor, edge_index, X_test_tensor)
    test_loss = criterion(predictions_test.squeeze(), y_test_tensor)
    test_losses.append(test_loss.item())

    # Store the best predictions
    if test_loss.item() < best_test_loss:
        best_test_loss = test_loss.item()
        best_train_predictions = predictions_train.clone()
        best_test_predictions = predictions_test.clone()
        torch.save(model.state_dict(), best_model_path)  # Save the best model

    # Calculate metrics for training set
    predictions_train_unscaled = np.concatenate([scalers_y[sensor_id].inverse_transform(best_train_predictions[idx:idx+len(df[df['sensor_id'] == sensor_id])-n_steps+1].detach().numpy().reshape(-1, 1)).flatten() for idx, sensor_id in enumerate(sensor_ids)], axis=0)
    y_train_unscaled = np.concatenate([scalers_y[sensor_id].inverse_transform(y_train[idx:idx+len(df[df['sensor_id'] == sensor_id])-n_steps+1].reshape(-1, 1)).flatten() for idx, sensor_id in enumerate(sensor_ids)], axis=0)

    # Calculate metrics for testing set
    predictions_test_unscaled = np.concatenate([scalers_y[sensor_id].inverse_transform(best_test_predictions[idx:idx+len(df[df['sensor_id'] == sensor_id])-n_steps+1].detach().numpy().reshape(-1, 1)).flatten() for idx, sensor_id in enumerate(sensor_ids)], axis=0)
    y_test_unscaled = np.concatenate([scalers_y[sensor_id].inverse_transform(y_test[idx:idx+len(df[df['sensor_id'] == sensor_id])-n_steps+1].reshape(-1, 1)).flatten() for idx, sensor_id in enumerate(sensor_ids)], axis=0)
   #print(f"{y_test_unscaled}, {predictions_test_unscaled}")
    train_rmse = np.sqrt(mean_squared_error(y_train_unscaled, predictions_train_unscaled))
    train_r2 = r2_score(y_train_unscaled, predictions_train_unscaled)
    train_mape = mean_absolute_percentage_error(y_train_unscaled, predictions_train_unscaled)

    test_rmse = np.sqrt(mean_squared_error(y_test_unscaled, predictions_test_unscaled))
    test_r2 = r2_score(y_test_unscaled, predictions_test_unscaled)
    test_mape = mean_absolute_percentage_error(y_test_unscaled, predictions_test_unscaled)

    train_rmse_values.append(train_rmse)
    train_r2_values.append(train_r2)
    train_mape_values.append(train_mape)
    test_rmse_values.append(test_rmse)
    test_r2_values.append(test_r2)
    test_mape_values.append(test_mape)
    end_time = time.time()  # Record end time
    epoch_time = end_time - start_time  # Calculate epoch time

    print(f"Epoch {epoch+1}/{num_epochs}, Time: {epoch_time:.2f} seconds, Train Loss: {train_loss.item()}, Test Loss: {test_loss.item()}, Train RMSE: {train_rmse}, Train R²: {train_r2}, Train MAPE: {train_mape}, Test RMSE: {test_rmse}, Test R²: {test_r2}, Test MAPE: {test_mape}")

import matplotlib.pyplot as plt

# Plotting train and test losses over epochs
plt.figure(figsize=(12, 6))

plt.subplot(2, 2, 1)
plt.plot(train_losses, label='Train Loss')
plt.plot(test_losses, label='Test Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('Train and Test Losses')
plt.legend()

# Plotting RMSE values over epochs
plt.subplot(2, 2, 2)
plt.plot(train_rmse_values, label='Train RMSE')
plt.plot(test_rmse_values, label='Test RMSE')
plt.xlabel('Epochs')
plt.ylabel('RMSE')
plt.title('Train and Test RMSE')
plt.legend()

# Plotting R² values over epochs
plt.subplot(2, 2, 3)
plt.plot(train_r2_values, label='Train R²')
plt.plot(test_r2_values, label='Test R²')
plt.xlabel('Epochs')
plt.ylabel('R²')
plt.title('Train and Test R²')
plt.legend()

# Plotting MAPE values over epochs
plt.subplot(2, 2, 4)
plt.plot(train_mape_values, label='Train MAPE')
plt.plot(test_mape_values, label='Test MAPE')
plt.xlabel('Epochs')
plt.ylabel('MAPE')
plt.title('Train and Test MAPE')
plt.legend()

plt.tight_layout()
plt.savefig(f'{plot_path}/epoch_op_plot.png')
plt.show()
plt.close()

for i in range(len(y_test_unscaled)):
  print(f"{y_test_unscaled[i]}, {predictions_test_unscaled[i]}")

import torch
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Load the trained model
num_features = X_train_tensor.shape[2]
num_nodes = X_train_tensor.shape[1]
#best_model_path = '/content/drive/MyDrive/Intellipaat-sem2/AirPollutionAnalysis/RG/best_model/best_model.pth'
print(f'best_model_path {best_model_path}')

model = AdvancedTemporalGraphNetwork(num_features=num_features, hidden_channels=16, num_nodes=num_nodes, dropout=0.2)
model.load_state_dict(torch.load(best_model_path, weights_only=True))  # Load the best model
model.eval()  # Set the model to evaluation mode

def prepare_future_data(future_dates, sensor_ids, scalers_X, sensor_location_map):
    """
    Prepare future data for forecasting with actual temperature & humidity.
    Args:
        future_dates: List of future dates (datetime objects).
        sensor_ids: List of sensor IDs.
        scalers_X: Dictionary of scalers for each sensor.
        sensor_location_map: Dictionary mapping sensor_id to (longitude, latitude).
        df: DataFrame containing historical data.
    Returns:
        X_future_tensor: Tensor of future data for prediction.
    """
    # Create DataFrame for future timestamps and sensor IDs
    future_df = pd.DataFrame({
        'timestamp': np.repeat(future_dates, len(sensor_ids)),
        'sensor_id': np.tile(sensor_ids, len(future_dates))
    })

    # Get latest temperature & humidity readings per sensor
    latest_readings = df.groupby('sensor_id')[['temperature', 'humidity']].last()

    # Map temperature & humidity from historical data
    future_df['temperature'] = future_df['sensor_id'].map(lambda x: latest_readings.loc[x, 'temperature'] if x in latest_readings.index else np.nan)
    future_df['humidity'] = future_df['sensor_id'].map(lambda x: latest_readings.loc[x, 'humidity'] if x in latest_readings.index else np.nan)

    # Fill missing values with median (or any strategy)
    future_df['temperature'].fillna(future_df['temperature'].median(), inplace=True)
    future_df['humidity'].fillna(future_df['humidity'].median(), inplace=True)

    # Map longitude and latitude from sensor_location_map
    future_df['longitude'] = future_df['sensor_id'].map(lambda x: sensor_location_map[x]['longitude'] if x in sensor_location_map else None)
    future_df['latitude'] = future_df['sensor_id'].map(lambda x: sensor_location_map[x]['latitude'] if x in sensor_location_map else None)

    # Extract time-based features
    future_df['year'] = future_df['timestamp'].dt.year
    future_df['month'] = future_df['timestamp'].dt.month
    future_df['day_of_month'] = future_df['timestamp'].dt.day
    future_df['hour'] = future_df['timestamp'].dt.hour
    future_df['minute'] = future_df['timestamp'].dt.minute
    future_df['second'] = future_df['timestamp'].dt.second

    # Drop timestamp column
    future_df = future_df.drop(columns=['timestamp'])

    # Scale features using the same scalers used during training
    X_future_scaled = []
    for sensor_id in sensor_ids:
        df_sensor = future_df[future_df['sensor_id'] == sensor_id].drop(columns=['sensor_id'])
        X_scaled = scalers_X[sensor_id].transform(df_sensor.to_numpy())
        X_future_scaled.append(X_scaled)

    # Combine scaled data
    X_future_scaled = np.concatenate(X_future_scaled, axis=0)

    # Ensure divisibility by num_nodes (padding if necessary)
    total_samples = X_future_scaled.shape[0]
    remainder = total_samples % num_nodes
    if remainder != 0:
        num_dummy_rows = num_nodes - remainder
        dummy_rows = np.zeros((num_dummy_rows, num_features))  # Zero padding
        X_future_scaled = np.vstack([X_future_scaled, dummy_rows])

    X_future_scaled = X_future_scaled.reshape(-1, num_nodes, num_features)

    # Convert to tensor
    X_future_tensor = torch.tensor(X_future_scaled, dtype=torch.float32)

    return X_future_tensor

# Define future dates for forecasting (every 15 minutes for the next 7 days)
future_dates = pd.date_range(start=pd.Timestamp.now().floor('D') + pd.Timedelta(days=1),  # Start from next day
                             end=pd.Timestamp.now().floor('D') + pd.Timedelta(days=8),    # End after 7 days
                             freq='15min')  # Frequency: 15 minutes

print(f'len future_dates {len(future_dates)}')
print(f'len sensor_ids {len(sensor_ids)}')


# Selecting relevant columns
sensor_location_map = df[['sensor_id', 'longitude', 'latitude']]
# Dropping duplicate sensor_id rows
sensor_location_map = sensor_location_map.drop_duplicates(subset='sensor_id')

# Setting index and converting to dictionary
sensor_location_map = sensor_location_map.set_index('sensor_id')[['longitude', 'latitude']].to_dict(orient='index')
print(sensor_location_map)

# Prepare future data
X_future_tensor = prepare_future_data(future_dates, sensor_ids, scalers_X, sensor_location_map)

# Generate predictions for future dates
with torch.no_grad():
    future_predictions = model(X_future_tensor, edge_index, X_future_tensor)

# Unscale the predictions
future_predictions_unscaled = np.concatenate([
    scalers_y[sensor_id].inverse_transform(future_predictions[idx:idx+len(future_dates)].detach().numpy().reshape(-1, 1)).flatten()
    for idx, sensor_id in enumerate(sensor_ids)
], axis=0)

# Create a DataFrame to store the predictions
future_predictions_df = pd.DataFrame({
    'timestamp': np.repeat(future_dates, len(sensor_ids)),
    'sensor_id': np.tile(sensor_ids, len(future_dates)),
    'predicted_pm2p5': future_predictions_unscaled
})

print(future_predictions_df)
# Save the predictions to a CSV file
future_predictions_df.to_csv(future_predictions_15min, index=False)


print("Future predictions saved to CSV.")

"""save with actual data"""